// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe-Ivwj1AozifwkLFhBu5-rNCmrkTnyME',
    appId: '1:33898652058:web:638012413a364df31d1a23',
    messagingSenderId: '33898652058',
    projectId: 'padelfever-dcd3b',
    authDomain: 'padelfever-dcd3b.firebaseapp.com',
    storageBucket: 'padelfever-dcd3b.firebasestorage.app',
    measurementId: 'G-08BY7EMXEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlEX3KeWCOyxGoWFs-dokuJ161hgWeyZc',
    appId: '1:33898652058:android:9fc7168a7c704e8b1d1a23',
    messagingSenderId: '33898652058',
    projectId: 'padelfever-dcd3b',
    storageBucket: 'padelfever-dcd3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg9FWiArW4NJ8h7PV3Vg9xKpA9rpi8lVg',
    appId: '1:33898652058:ios:fadb49d77391cc781d1a23',
    messagingSenderId: '33898652058',
    projectId: 'padelfever-dcd3b',
    storageBucket: 'padelfever-dcd3b.firebasestorage.app',
    iosBundleId: 'com.example.padelpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg9FWiArW4NJ8h7PV3Vg9xKpA9rpi8lVg',
    appId: '1:33898652058:ios:fadb49d77391cc781d1a23',
    messagingSenderId: '33898652058',
    projectId: 'padelfever-dcd3b',
    storageBucket: 'padelfever-dcd3b.firebasestorage.app',
    iosBundleId: 'com.example.padelpoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe-Ivwj1AozifwkLFhBu5-rNCmrkTnyME',
    appId: '1:33898652058:web:8bf4716be31efbef1d1a23',
    messagingSenderId: '33898652058',
    projectId: 'padelfever-dcd3b',
    authDomain: 'padelfever-dcd3b.firebaseapp.com',
    storageBucket: 'padelfever-dcd3b.firebasestorage.app',
    measurementId: 'G-6EY5THHZQG',
  );
}
